[package]
name = "cf-user_integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
ulid = "1.0.0"